### ISSUE TITLE
start_rtorrent.c

### ISSUE THREAD

**Issue by exrat** [Magicalex/seedbox-manager#14]
Salut les gars !
Est-ce que ce serait envisageable d'ajouter le démarrage d'irssi dans **start_rtorrent.c** ?
Avec le script je le lance en /etc/rc.local avec la commande:
`/bin/su exrat -c "/usr/bin/screen -dmS irc_logger /usr/bin/irssi"`
Pour l'instant ça oblige le gars à faire un
`/etc/rc.local &`
à la main en cas de relance avec le kill des screen user, c'est pas pratique on va dire ^^
Je savais que ça aller être une galère ce plugin autodl-irssi...
Ex.

**Comment by MThibault** [comment]
Salut,
J'y vois aucun problème en soit, le seul souci est que l'utilisateur qui n'a pas irssi d'installer aura une erreur. Ou alors je peux checker si irssi est présent sur le serveur.

Mais cela ne signifie pas qu'il utilise le plugin d'autodl, et il n'a peut etre pas besoin d'etre relancé avec le relancement de rtorrent.

J'ai plus trop suivi les derniers devs de l'interface de Magicalex.
Avec un peu de remise en contexte, je pourrais peut etre trouver une solution plus propre.

**Comment by Magicalex** [comment]
@MThibault j'ai presque pas modifié le programme que tu as fait.
La seul solution que je vois c'est de lancer irssi en option genre.

```bash
./reboot-rtorrent --with-irssi <username>
```

**Comment by MThibault** [comment]
@Magicalex Je parle pas du programme, mais de ton outil web et de toutes ses fonctionnalités.
Je regarde cette idée

**Comment by Magicalex** [comment]
Non l'interface web n'a pas changé depuis on bon moment.

**Comment by MThibault** [comment]
@Magicalex @exrat Actuellement, on envoie uniquement le username au programme en C.
Le username pour irssi doit il etre le mm? ou peut il etre différent?

**Comment by exrat** [comment]
Salut MThibault
L'username est le même pour irssi et rtorrent si c'est bien la question ;)

**Comment by MThibault** [comment]
Ok, parfait :)

**Comment by MThibault** [comment]
@exrat tu peux me donner la commande pour kill irssi, et pour le lancer stp

**Comment by MThibault** [comment]
@exrat et aussi, il faut que irssi soit tué et relancé avant ou après rtorrent?

**Comment by exrat** [comment]
J'ai pas de kill irssi dans le script auto, je tue juste les screen en bloc si besoin du coup je ne sais pas ^^
Pour lancer un user "exrat", j'utilise juste ça:
`/bin/su exrat -c "/usr/bin/screen -dmS irc_logger /usr/bin/irssi"`

**Comment by exrat** [comment]
je le fais après rtorrent mais ça doit pas être vital

**Comment by MThibault** [comment]
Ok très bien merci.
Je suis entrain de faire le reboot.
Seul truc, quand on met des chemins absolues on peut avoir des soucis sur des systèmes modifiés ou exotiques.
Soit je mets :
 su exrat -c "screen -dmS irc_logger irssi"
Soit je vérifie les chemins de tous les exécutables avant de créer la commande (plus lourd)

**Comment by exrat** [comment]
l'environnement "logiquement" ne devrait pas être exotique vu les prérequis et limites du script auto (debian 7/8 only) donc fais au plus simple à mon avis

**Comment by MThibault** [comment]
Bon, vu que tu as juste besoin du start, je pense que c'est codé.
Juste que je revois comment faire un pull request ahah

**Comment by exrat** [comment]
De la balle, je te remercie !
Par contre, je ne pourrai tester que lundi, je prends la route dans quelques minutes direction loin du web.

**Comment by MThibault** [comment]
Pas de souci, je peux pas tester, mais prends ton temps.
Profites du we.

**Comment by MThibault** [comment]
@Magicalex Oups, j'ai pushé, et ca a changé la branche courante...
Je suis dsl, j'ai un peu perdu l'habitude. tu veux faire un revert?

**Comment by MThibault** [comment]
@Magicalex Rajouter dans la doc que l'usage pour irssi est :
./reboot-rtorrent <username> irssi

**Comment by Magicalex** [comment]
Non pas besoins de revert. Pas besoins de faire une pull request t'as un accès direct à tout les branch aussi.

**Comment by MThibault** [comment]
Parfait, je pense que c'est tout bon.
Oui je pense que c'est le mieux @Magicalex 
A la rigueur tu vérifies si irssi est installé, et si c'est le cas, le bouton apparait sur l'interface admin de la seedbox

**Comment by exrat** [comment]
Un bouton à part "reboot-irssi" serait peut-être pas mal oui.
Alors j'ai testé ce matin et ça fait pas tout à fait le job apparemment (à moins que j'ai merdé quelque part...)
J'ai modifié main.c et ajouté les 2 nouveaux start_irssi.c et start_irssi.h (+ chown www-data)
Si je fais tomber rTorrent et irssi en tuant les screen, irssi ne se relance pas.
Dans le log de smb j'ai seulement ça, il ne parle pas d'irssi:

commande exécutée : reboot-rtorrent exrat
statut : 0
résultat de la commande : 
 setuid: Success
 rtorrent: no process found
 killall --user exrat rtorrent
 su --command='screen -S exrat-rtorrent -X quit' exrat
 rm /home/exrat/.session/rtorrent.lock
 su --command='screen -dmS exrat-rtorrent rtorrent' exrat

@Magicalex ou @MThibault , si vous voulez tester en live et regarder de plus prêt, j'ai un kim tout propre installé bonobox à dispo

**Comment by MThibault** [comment]
@exrat Quelle commande as tu lancé pour faire ton test stp?

**Comment by MThibault** [comment]
`sudo ./prog toto`
> setuid: Success
su --command='screen -S toto-rtorrent -X quit' toto
rm /home/toto/.session/rtorrent.lock
su --command='screen -dmS toto-rtorrent rtorrent' toto

`sudo ./prog toto irssi`
> setuid: Success
su --command='screen -S toto-rtorrent -X quit' toto
rm /home/toto/.session/rtorrent.lock
su --command='screen -dmS toto-rtorrent rtorrent' toto
su --command='screen -dmS irc_logger irssi' toto

Voici un petit débug, ca semble fonctionner.
Après j'ai pas l'environnement.

**Comment by exrat** [comment]
Désolé pour le temps de réponse, je suis noyé de boulot cette semaine donc c'est pas facile.

J'ai ajouté les dernières modif' à la main: main.c, start_irssi.c et start_irssi.h + chown www-data pour être raccord avec le reste.
Ensuite j'ai tué mon user comme ça:
killall --user exrat rtorrent
killall --user exrat screen
et juste utilisé le bouton "redémarré rtorrent" de seedbox-manager.

Si tu veux voir le truc de plus prêt, tu peux me balancer un mail sur ex_rat@protonmail.com et je te fais passer toutes les infos de connexion, ce serait peut-être plus pratique pour voir à quoi ça ressemble parce que je sens mal parti là...

**Comment by MThibault** [comment]
Pas de souci.

Si tu n'as pas modifier le code du bouton redémarrer rtorrent, c'est normal, car il faut rajouter le param "irssi".
Le reboot doit se faire ainsi : ./reboot-rtorrent username irssi

**Comment by Magicalex** [comment]
@exrat j'ai pas ajouté l'option pour redémarrer irssi c'est normale que ça fonctionne pas

**Comment by exrat** [comment]
Ok, donc toujours entre deux portes... J'ai cherché pour le bouton mais pas trouvé pour modifier, ça me dépasse un peu :(

En lançant à la main, j'ai pas de irssi. Je ne pensais pas que ce serait chatouilleux comme ça ^^

root@ksxxx:/var/www/seedbox-manager# ./reboot-rtorrent exrat irssi
setuid: Success
killall --user exrat rtorrent
rtorrent: aucun processus trouvé
su --command='screen -S exrat-rtorrent -X quit' exrat
No screen session found.
rm /home/exrat/.session/rtorrent.lock
su --command='screen -dmS exrat-rtorrent rtorrent' exrat

rahhh, je repars bosser jusqu'à tard ce soir là :(

**Comment by MThibault** [comment]
Je suis pas sur que tu ais la dernière version, car tu aurais au moins du avoir une ligne de log pour irssi, ca signifie que tu es pas rentré dans la fonction.

**Comment by MThibault** [comment]
@exrat Tu as pas les bonnes versions des fichiers .c
il faudrait que tu clones tout le projet, ou au moins celui du programme en C.

**Comment by Magicalex** [comment]
yes exrat il faut recompiler reboot-rtorrent.
Tu peux le faire via le script install.sh

**Comment by MThibault** [comment]
@exrat C'est bon, je t'ai mis les nouveaux fichiers pour le programme en C.
Je l'ai recompilé avec le script, tout s'est bien passé.
Je l'ai testé, et comme envoyé par mail, ca marche, tu as la trace d'execution corresopndant aux logs du programme, et tu peux aussi vérifier les processus lancés qui te montrent bien rtorrent et irssi.

**Comment by exrat** [comment]
Ça marche très bien, merci pour la modif @MThibault  :D
@Magicalex est-ce qu'il va falloir que je tape sur github après pour installé avec le script ou tu comptes mettre à jour ? Parce qu'avec la méthode "composer" du tuto mondedie, j'ai des fichiers qui date de juin 2015 là.
Et pour le bouton, tu vas nous bricoler un truc ? J'ai fourgonné un peu, j'ai absolument aucunes idées de comment ça marche cette affaire ^^
Ex.

**Comment by MThibault** [comment]
Au besoin, je peux te faire une solution temporaire je pense

**Comment by exrat** [comment]
C'est peut-être mieux d'attendre de voir comment Magicalex voit le truc, pour pas que ça coince si les mecs décident de faire une mise à jour derrière. Parce que je tente toujours d'être le plus standard possible pour la santé de ma boite à MP, je deviens vite responsable de tous leurs malheurs avec le script ^^

**Comment by MThibault** [comment]
Bon, je te laisse les cartes en main.
Sur ton serveur, j'ai modifié le fichier app/Lib/Users.php
J'ai commenté la ligne 80 qui est l'ancienne ligne pour la fonction reboot-rtorrent.
La ligne 81 est la nouvelle pour laquelle j'ai ajouté irssi.
Ca va te permettre de tester déjà.
Donc si tu veux revenir en arrière, tu supprimes la ligne 81 et décommentes la ligne 80.
Je vous fais un retour plus tard.

**Comment by exrat** [comment]
Ok, je vais me sauvegarder tout ça, je te remercie :)

**Comment by MThibault** [comment]
Je viens de faire le test sur ton serveur.
Seul souci, est que quand tu rebootes rtorrent, comme on ne kill pas irssi (comme expliqué au début), on lance une deuxième instance d'irssi ....

**Comment by exrat** [comment]
Je suis en train de voir pour le lancer en tant que service avec un start/stop, ce qui serait plus propre, mais pour l'instant ça marche pas fort...
Mais je suis persévérant, je vais finir par m'en sortir \0/

**Comment by Magicalex** [comment]
@MThibault ouaip faudrait kill irssi avant de le lancer dans screen.
Moi je bricole une solution, avant j'ai du mettre une lib à moi à jour [write-ini-file](https://github.com/Magicalex/WriteiniFile) que j'utilise pour seedbox manager.

**Comment by MThibault** [comment]
@Magicalex C'est bon j'ai ajouté la fonctionnalité pour kill irssi. Et je l'ai testé sur le serveur de exrat, ca semble bien marché
@exrat J'ai mi en place sur ton serveur la dernière version du programme en C, j'ai testé, et ca a bien fonctionné.

**Comment by Magicalex** [comment]
c'est bon j'ai fais le nécéssaire, jsuis passé à la version 2.5.0 au passage.
J'attends ton retour pour fermer cette issue @exrat

**Comment by MThibault** [comment]
@exrat Je te remets le fichier app/Lib/Users.php dans l'état de base, comme ca tu as juste à mettre à jour normalement.

**Comment by Magicalex** [comment]
http://images.mondedie.fr/T3oNyGjD/H4An2Ye2.png

**Comment by exrat** [comment]
Je viens de faire une install' en vitesse, ça fait le job parfaitement et la case a cocher est impec.
Merci les gars, on peut fermer et repartir vers de nouvelles aventures ! ;)
Ex.
