### ISSUE TITLE
mettre a jour avec derniere version

### ISSUE THREAD

**Issue by kris1208** [Magicalex/seedbox-manager#16]
Bonjour,
comment mettre a jour la seedbox et rajouter cakebox,
J'ai essayer en root de faire un apt-get update mais a la fin ca me donne un message erreur, j'ai donc fait apt-get upgrade ca a mouliné un moment mais pas certain d'avoir la bonne version, je suis en 2.4.4.
Merci

**Comment by Hydrog3n** [comment]
Salut, 
Je crois que tu confonds quelque chose. Tu souhaites mettre quoi à jours ? Cakebox, seedbox manager ou des paquets debian ?
