### ISSUE TITLE
Login:

### ISSUE THREAD

**Issue by Kongledyret** [Magicalex/seedbox-manager#17]
Hi!

I have installed the script, but it tells me username/password. 
How to fix this?

**Comment by Magicalex** [comment]
Hi,

In your webserver configuration, you need to add "http basic authentication".
For nginx http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html
For apache https://httpd.apache.org/docs/2.2/fr/mod/mod_auth_basic.html

**Comment by Kongledyret** [comment]
Ok fixed that :) any translations for the GUI?

**Comment by Magicalex** [comment]
> any translations for the GUI?

@Kongledyret for the next version (v3)

**Comment by Kongledyret** [comment]
Ok Nice!

**Comment by Magicalex** [comment]
v3 is here https://github.com/Magicalex/seedbox-manager/releases/tag/v3.0.0
