### ISSUE TITLE
Add new users -

### ISSUE THREAD

**Issue by Kongledyret** [Magicalex/seedbox-manager#18]
Hi!
Is there a way to add new users through adminpanel? If not, will it come in future update(s)?

**Comment by al3xLvs** [comment]
For create a new user, just log in with the credentials. (users files configuration is automatically generated)
After, you can configure user with admin user.

**Comment by Kongledyret** [comment]
Hi, 
I cannot get this to work. I try to login with random user/pass in the popup window, but it doesnt add anything to the users files.
