### ISSUE TITLE
Problème dans le XML de FileZila

### ISSUE THREAD

**Issue by Hydrog3n** [Magicalex/seedbox-manager#9]
Il y a un problème lorsque le mot de passe comprend le caractère "<" Filezila n'aime pas. 

Il faudrait voir comment contourner ce soucis, je n'utilise pas du filezila

http://mondedie.fr/viewtopic.php?pid=21259

**Comment by Micdu70** [comment]
Voilà, j'ai mis en place une solution à ce problème, voir mon "pull request" #10. =)

**Comment by Hydrog3n** [comment]
Efficace ! Merci à toi.

**Comment by Magicalex** [comment]
merci j'ai merge,@Micdu70 tu peux me dire pourquoi tu utilises l'option ENT_NOQUOTES ?

@Hydrog3n tu peux utiliser le fichier de config filezilla, pour configurer transmit
Favoris -> importer depuis -> filezilla

**Comment by Micdu70** [comment]
L'option ENT_NOQUOTES permet de ne pas convertir les guillemets doubles et les guillemets simples => http://php.net/manual/fr/function.htmlspecialchars.php

C'est inutile de convertir les guillements car ils ne posent pas de problème dans le XML. Seul "<" et "&" posent problème dans notre cas. ( Le ">" est converti aussi mais il ne pose pas de problème pour FileZilla )

**Comment by Magicalex** [comment]
Oui effectivement, c'est pertinent après reflexion.
Merci encore pour la correction du bug.
